-- noinspection SqlNoDataSourceInspectionForFile

create table role (id bigint generated by default as identity, name varchar(255), primary key (id));
create table user (id bigint generated by default as identity, created binary(255) not null, email varchar(255) not null, enabled boolean not null, password varchar(255) not null, username
                      varchar(255) not null, primary key (id));
create table user_role (id bigint generated by default as identity, role_id bigint, user_id bigint, primary key (id));
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user_role add constraint UK872xec3woupu3gw59b04pj3sa unique (user_id, role_id);

TRUNCATE TABLE role;
TRUNCATE TABLE user;
TRUNCATE TABLE user_role;
COMMIT;

INSERT INTO role(id, name) VALUES (1, 'ROLE_USER');
INSERT INTO role(id, name) VALUES (2, 'ROLE_ADMIN');

COMMIT;
